---
#https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html
- hosts:  pvenodes
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
      
  vars_files:
    - vars/api-key.yaml
    - vars/vars.yaml
  
  tasks:
  - name: Create vm with min options
    proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  "{{ node }}"
      node: "{{ node }}"
      name: vmtest01
      cores: 2
      memory: 1024
      sata:
        sata0: "{{ storage }}:30,format=raw"