#https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html
- hosts:  pvenodes
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
      
  vars_files:
    - vars/api-key.yaml
  
  tasks:

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3smast01
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3smast02
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3smast03
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3swork01
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3work02
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500

  - name: Clone VM
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: "{{ api_key }}"
      api_host:  pvenodes
      node: smac
      clone: ubuntu-cloud-template
      name: k3work03
      storage: LinuxVMs
      full: true
      format: unspecified
      timeout: 500