- hosts: pvenodes
  vars_files:
    - vars/ssh-key.yaml
  tasks:

    - name: install sudo package
      apt:
        name: sudo
        cache_valid_time:  3600
        state: latest
    
    - name: create Ansible user
      user:
        name: ansible
        shell: '/bin/bash'
    
    - name: add Ansible ssh key
      authorized_key:
        user: ansible
        key: "{{ ssh-key }}"

    - name:  add ansible to sudoers
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440
